//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MXApp.MobileService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string Vendor__ { get; set; }
        public Nullable<int> ModType { get; set; }
        public string Vendor_Name { get; set; }
        public string Phone__ { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip_Code { get; set; }
        public string Vendor_Manager { get; set; }
        public string WHS { get; set; }
        public string CO { get; set; }
        public string AcctBillingName { get; set; }
        public string AcctBillingName2 { get; set; }
        public string AcctBillingAddress1 { get; set; }
        public string AcctBillingAddress2 { get; set; }
        public string AcctBillingCity { get; set; }
        public string AcctBillingState { get; set; }
        public string AcctBillingPostal { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<bool> FreezInv { get; set; }
        public Nullable<bool> EDIAccount { get; set; }
        public Nullable<bool> EDIWAVEAccount { get; set; }
        public string BillingMiscInfo1 { get; set; }
        public string BillingMiscInfo2 { get; set; }
        public string BillingMiscInfo3 { get; set; }
        public Nullable<bool> Need944 { get; set; }
        public Nullable<bool> Need856 { get; set; }
        public string MapPath944 { get; set; }
        public string MapPath856 { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string FilePath944 { get; set; }
        public string FilePath856 { get; set; }
        public string SKUAllocType { get; set; }
        public string acc_billing_email { get; set; }
        public string acc_inventory_email { get; set; }
    }
}
