//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MXApp.MobileService
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDIAppTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EDIAppTable()
        {
            this.EDIAppTable_Child = new HashSet<EDIAppTable_Child>();
        }
    
        public int EDIAPPID { get; set; }
        public string PickUp_LoadNum { get; set; }
        public Nullable<bool> IsLTL { get; set; }
        public string WHS { get; set; }
        public Nullable<System.DateTime> PUDate { get; set; }
        public Nullable<System.DateTime> PUTime { get; set; }
        public string Carrier { get; set; }
        public string SCAC { get; set; }
        public string SealNumber { get; set; }
        public Nullable<bool> CarryOverNextDay { get; set; }
        public Nullable<bool> IsShipped { get; set; }
        public Nullable<bool> IsVoided { get; set; }
        public Nullable<bool> IsPrint { get; set; }
        public Nullable<bool> UPSFedEx { get; set; }
        public string AppIDComments { get; set; }
        public string DepartingDoor { get; set; }
        public Nullable<int> LoadPalletCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EDIAppTable_Child> EDIAppTable_Child { get; set; }
    }
}
