//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MXApp.MobileService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SkyNetEntities : DbContext
    {
        public SkyNetEntities()
            : base("name=SkyNetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<WMS_Explorer> WMS_Explorer { get; set; }
        public virtual DbSet<POD_Repository> POD_Repository { get; set; }
        public virtual DbSet<RefCode> RefCodes { get; set; }
        public virtual DbSet<View_WHS> View_WHS { get; set; }
        public virtual DbSet<EDIAppTable> EDIAppTables { get; set; }
        public virtual DbSet<EDIAppTable_Child> EDIAppTable_Child { get; set; }
        public virtual DbSet<login> logins { get; set; }
    
        public virtual ObjectResult<sp_mob_OpenProdWO_Result> sp_mob_OpenProdWO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mob_OpenProdWO_Result>("sp_mob_OpenProdWO");
        }
    
        public virtual int sp_mob_UpdateWOStart(Nullable<int> rEFNUM)
        {
            var rEFNUMParameter = rEFNUM.HasValue ?
                new ObjectParameter("REFNUM", rEFNUM) :
                new ObjectParameter("REFNUM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mob_UpdateWOStart", rEFNUMParameter);
        }
    
        public virtual ObjectResult<sp_mob_AddProdWODetails_Result> sp_mob_AddProdWODetails(string account)
        {
            var accountParameter = account != null ?
                new ObjectParameter("Account", account) :
                new ObjectParameter("Account", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mob_AddProdWODetails_Result>("sp_mob_AddProdWODetails", accountParameter);
        }
    
        public virtual ObjectResult<sp_mob_ListProdWODetails_Result> sp_mob_ListProdWODetails(Nullable<int> rEFNUM)
        {
            var rEFNUMParameter = rEFNUM.HasValue ?
                new ObjectParameter("REFNUM", rEFNUM) :
                new ObjectParameter("REFNUM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mob_ListProdWODetails_Result>("sp_mob_ListProdWODetails", rEFNUMParameter);
        }
    
        public virtual int sp_mob_DeleteProdWODetails(Nullable<int> codeID)
        {
            var codeIDParameter = codeID.HasValue ?
                new ObjectParameter("CodeID", codeID) :
                new ObjectParameter("CodeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mob_DeleteProdWODetails", codeIDParameter);
        }
    
        public virtual int sp_mob_UpdateBillCode(Nullable<int> rEFNUM, Nullable<int> billCode)
        {
            var rEFNUMParameter = rEFNUM.HasValue ?
                new ObjectParameter("REFNUM", rEFNUM) :
                new ObjectParameter("REFNUM", typeof(int));
    
            var billCodeParameter = billCode.HasValue ?
                new ObjectParameter("BillCode", billCode) :
                new ObjectParameter("BillCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mob_UpdateBillCode", rEFNUMParameter, billCodeParameter);
        }
    
        public virtual int sp_mob_UpdateProdWODetails(Nullable<int> codeID, Nullable<int> qTY, string billComments)
        {
            var codeIDParameter = codeID.HasValue ?
                new ObjectParameter("CodeID", codeID) :
                new ObjectParameter("CodeID", typeof(int));
    
            var qTYParameter = qTY.HasValue ?
                new ObjectParameter("QTY", qTY) :
                new ObjectParameter("QTY", typeof(int));
    
            var billCommentsParameter = billComments != null ?
                new ObjectParameter("BillComments", billComments) :
                new ObjectParameter("BillComments", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mob_UpdateProdWODetails", codeIDParameter, qTYParameter, billCommentsParameter);
        }
    
        public virtual int sp_mob_ConfirmProdWODetails(Nullable<int> rEFNUM)
        {
            var rEFNUMParameter = rEFNUM.HasValue ?
                new ObjectParameter("REFNUM", rEFNUM) :
                new ObjectParameter("REFNUM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mob_ConfirmProdWODetails", rEFNUMParameter);
        }
    
        public virtual int sp_mob_AppendProdWODetails(string account, string rEFNUM, Nullable<int> bILLID)
        {
            var accountParameter = account != null ?
                new ObjectParameter("Account", account) :
                new ObjectParameter("Account", typeof(string));
    
            var rEFNUMParameter = rEFNUM != null ?
                new ObjectParameter("REFNUM", rEFNUM) :
                new ObjectParameter("REFNUM", typeof(string));
    
            var bILLIDParameter = bILLID.HasValue ?
                new ObjectParameter("BILLID", bILLID) :
                new ObjectParameter("BILLID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mob_AppendProdWODetails", accountParameter, rEFNUMParameter, bILLIDParameter);
        }
    
        public virtual int sp_mob_TimeTrack_ClockIn_Out_Employee(Nullable<int> rEFNUM, Nullable<int> bADGEID, Nullable<int> type, Nullable<int> temp, Nullable<int> woNuMID)
        {
            var rEFNUMParameter = rEFNUM.HasValue ?
                new ObjectParameter("REFNUM", rEFNUM) :
                new ObjectParameter("REFNUM", typeof(int));
    
            var bADGEIDParameter = bADGEID.HasValue ?
                new ObjectParameter("BADGEID", bADGEID) :
                new ObjectParameter("BADGEID", typeof(int));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            var tempParameter = temp.HasValue ?
                new ObjectParameter("temp", temp) :
                new ObjectParameter("temp", typeof(int));
    
            var woNuMIDParameter = woNuMID.HasValue ?
                new ObjectParameter("WoNuMID", woNuMID) :
                new ObjectParameter("WoNuMID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mob_TimeTrack_ClockIn_Out_Employee", rEFNUMParameter, bADGEIDParameter, typeParameter, tempParameter, woNuMIDParameter);
        }
    
        public virtual ObjectResult<sp_mob_TimeTrack_ListEmployee_Result> sp_mob_TimeTrack_ListEmployee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mob_TimeTrack_ListEmployee_Result>("sp_mob_TimeTrack_ListEmployee");
        }
    
        public virtual ObjectResult<sp_mob_GetWorkOrderReportHeader_Result> sp_mob_GetWorkOrderReportHeader(Nullable<int> rEFNUM)
        {
            var rEFNUMParameter = rEFNUM.HasValue ?
                new ObjectParameter("REFNUM", rEFNUM) :
                new ObjectParameter("REFNUM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mob_GetWorkOrderReportHeader_Result>("sp_mob_GetWorkOrderReportHeader", rEFNUMParameter);
        }
    
        public virtual int sp_mob_ship_loadshow_yesno_confirm(string lOADNUM, Nullable<int> type)
        {
            var lOADNUMParameter = lOADNUM != null ?
                new ObjectParameter("LOADNUM", lOADNUM) :
                new ObjectParameter("LOADNUM", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mob_ship_loadshow_yesno_confirm", lOADNUMParameter, typeParameter);
        }
    
        public virtual int sp_mob_ship_loadshow_yesno_confirmdetail(string mBOLVICS, Nullable<int> type)
        {
            var mBOLVICSParameter = mBOLVICS != null ?
                new ObjectParameter("MBOLVICS", mBOLVICS) :
                new ObjectParameter("MBOLVICS", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mob_ship_loadshow_yesno_confirmdetail", mBOLVICSParameter, typeParameter);
        }
    
        public virtual int sp_mob_ship_loadshow_yesno_confirmmaster(Nullable<int> type, Nullable<int> eDIAPPID)
        {
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            var eDIAPPIDParameter = eDIAPPID.HasValue ?
                new ObjectParameter("EDIAPPID", eDIAPPID) :
                new ObjectParameter("EDIAPPID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mob_ship_loadshow_yesno_confirmmaster", typeParameter, eDIAPPIDParameter);
        }
    
        public virtual ObjectResult<sp_mob_ship_viewloaddetails_Result> sp_mob_ship_viewloaddetails(Nullable<int> eDIAPPID)
        {
            var eDIAPPIDParameter = eDIAPPID.HasValue ?
                new ObjectParameter("EDIAPPID", eDIAPPID) :
                new ObjectParameter("EDIAPPID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mob_ship_viewloaddetails_Result>("sp_mob_ship_viewloaddetails", eDIAPPIDParameter);
        }
    
        public virtual ObjectResult<sp_mob_ship_viewloads_Result> sp_mob_ship_viewloads(string wHS, Nullable<System.DateTime> dATE)
        {
            var wHSParameter = wHS != null ?
                new ObjectParameter("WHS", wHS) :
                new ObjectParameter("WHS", typeof(string));
    
            var dATEParameter = dATE.HasValue ?
                new ObjectParameter("DATE", dATE) :
                new ObjectParameter("DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mob_ship_viewloads_Result>("sp_mob_ship_viewloads", wHSParameter, dATEParameter);
        }
    
        public virtual ObjectResult<sp_mob_ship_viewloads_locations_Result> sp_mob_ship_viewloads_locations(string lOADNUM)
        {
            var lOADNUMParameter = lOADNUM != null ?
                new ObjectParameter("LOADNUM", lOADNUM) :
                new ObjectParameter("LOADNUM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mob_ship_viewloads_locations_Result>("sp_mob_ship_viewloads_locations", lOADNUMParameter);
        }
    
        public virtual ObjectResult<sp_mob_prod_WOHourDetails_Result> sp_mob_prod_WOHourDetails(Nullable<int> rEFNUM)
        {
            var rEFNUMParameter = rEFNUM.HasValue ?
                new ObjectParameter("REFNUM", rEFNUM) :
                new ObjectParameter("REFNUM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mob_prod_WOHourDetails_Result>("sp_mob_prod_WOHourDetails", rEFNUMParameter);
        }
    
        [DbFunction("SkyNetEntities", "tf_mob_prod_CalcWOHours")]
        public virtual IQueryable<tf_mob_prod_CalcWOHours_Result> tf_mob_prod_CalcWOHours(Nullable<int> rEFNUM)
        {
            var rEFNUMParameter = rEFNUM.HasValue ?
                new ObjectParameter("REFNUM", rEFNUM) :
                new ObjectParameter("REFNUM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tf_mob_prod_CalcWOHours_Result>("[SkyNetEntities].[tf_mob_prod_CalcWOHours](@REFNUM)", rEFNUMParameter);
        }
    
        public virtual ObjectResult<sp_mob_TimeTrack_GetClockedInEmployees_Result> sp_mob_TimeTrack_GetClockedInEmployees(Nullable<int> rEFNUM)
        {
            var rEFNUMParameter = rEFNUM.HasValue ?
                new ObjectParameter("REFNUM", rEFNUM) :
                new ObjectParameter("REFNUM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mob_TimeTrack_GetClockedInEmployees_Result>("sp_mob_TimeTrack_GetClockedInEmployees", rEFNUMParameter);
        }
    
        public virtual int sp_mob_TimeTrack_ClockoutAll(Nullable<int> rEFNUM)
        {
            var rEFNUMParameter = rEFNUM.HasValue ?
                new ObjectParameter("REFNUM", rEFNUM) :
                new ObjectParameter("REFNUM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mob_TimeTrack_ClockoutAll", rEFNUMParameter);
        }
    }
}
