//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MXApp.MobileService
{
    using System;
    using System.Collections.Generic;
    
    public partial class POD_Repository
    {
        public int PODID { get; set; }
        public string PODKey { get; set; }
        public string PODDescription { get; set; }
        public string PODLink { get; set; }
        public System.DateTime PODBorn { get; set; }
        public string PODCreatedBy { get; set; }
    }
}
