using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MXApp.MobileService.Helpers
{
    public static class EmailBodyFormatter
    {
        public static string GetAllocationReportEmailBody()
        {
            // BuildMyString.com generated code. Please enjoy your string responsibly.

            StringBuilder sb = new StringBuilder();

            sb.Append("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional //EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"><html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\"><head>");
            sb.Append("    <!--[if gte mso 9]><xml>");
            sb.Append("     <o:OfficeDocumentSettings>");
            sb.Append("      <o:AllowPNG/>");
            sb.Append("      <o:PixelsPerInch>96</o:PixelsPerInch>");
            sb.Append("     </o:OfficeDocumentSettings>");
            sb.Append("    </xml><![endif]-->");
            sb.Append("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">");
            sb.Append("    <meta name=\"viewport\" content=\"width=device-width\">");
            sb.Append("    <!--[if !mso]><!--><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><!--<![endif]-->");
            sb.Append("    <title></title>");
            sb.Append("    <!--[if !mso]><!-- -->");
            sb.Append("	<link href=\"https://fonts.googleapis.com/css?family=Montserrat\" rel=\"stylesheet\" type=\"text/css\">");
            sb.Append("	<link href=\"https://fonts.googleapis.com/css?family=Lato\" rel=\"stylesheet\" type=\"text/css\">");
            sb.Append("	<!--<![endif]-->");
            sb.Append("    ");
            sb.Append("    <style type=\"text/css\" id=\"media-query\">");
            sb.Append("      body {");
            sb.Append("  margin: 0;");
            sb.Append("  padding: 0; }");
            sb.Append("table, tr, td {");
            sb.Append("  vertical-align: top;");
            sb.Append("  border-collapse: collapse; }");
            sb.Append(".ie-browser table, .mso-container table {");
            sb.Append("  table-layout: fixed; }");
            sb.Append("* {");
            sb.Append("  line-height: inherit; }");
            sb.Append("a[x-apple-data-detectors=true] {");
            sb.Append("  color: inherit !important;");
            sb.Append("  text-decoration: none !important; }");
            sb.Append("[owa] .img-container div, [owa] .img-container button {");
            sb.Append("  display: block !important; }");
            sb.Append("[owa] .fullwidth button {");
            sb.Append("  width: 100% !important; }");
            sb.Append("[owa] .block-grid .col {");
            sb.Append("  display: table-cell;");
            sb.Append("  float: none !important;");
            sb.Append("  vertical-align: top; }");
            sb.Append(".ie-browser .num12, .ie-browser .block-grid, [owa] .num12, [owa] .block-grid {");
            sb.Append("  width: 620px !important; }");
            sb.Append(".ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {");
            sb.Append("  line-height: 100%; }");
            sb.Append(".ie-browser .mixed-two-up .num4, [owa] .mixed-two-up .num4 {");
            sb.Append("  width: 204px !important; }");
            sb.Append(".ie-browser .mixed-two-up .num8, [owa] .mixed-two-up .num8 {");
            sb.Append("  width: 408px !important; }");
            sb.Append(".ie-browser .block-grid.two-up .col, [owa] .block-grid.two-up .col {");
            sb.Append("  width: 310px !important; }");
            sb.Append(".ie-browser .block-grid.three-up .col, [owa] .block-grid.three-up .col {");
            sb.Append("  width: 206px !important; }");
            sb.Append(".ie-browser .block-grid.four-up .col, [owa] .block-grid.four-up .col {");
            sb.Append("  width: 155px !important; }");
            sb.Append(".ie-browser .block-grid.five-up .col, [owa] .block-grid.five-up .col {");
            sb.Append("  width: 124px !important; }");
            sb.Append(".ie-browser .block-grid.six-up .col, [owa] .block-grid.six-up .col {");
            sb.Append("  width: 103px !important; }");
            sb.Append(".ie-browser .block-grid.seven-up .col, [owa] .block-grid.seven-up .col {");
            sb.Append("  width: 88px !important; }");
            sb.Append(".ie-browser .block-grid.eight-up .col, [owa] .block-grid.eight-up .col {");
            sb.Append("  width: 77px !important; }");
            sb.Append(".ie-browser .block-grid.nine-up .col, [owa] .block-grid.nine-up .col {");
            sb.Append("  width: 68px !important; }");
            sb.Append(".ie-browser .block-grid.ten-up .col, [owa] .block-grid.ten-up .col {");
            sb.Append("  width: 62px !important; }");
            sb.Append(".ie-browser .block-grid.eleven-up .col, [owa] .block-grid.eleven-up .col {");
            sb.Append("  width: 56px !important; }");
            sb.Append(".ie-browser .block-grid.twelve-up .col, [owa] .block-grid.twelve-up .col {");
            sb.Append("  width: 51px !important; }");
            sb.Append("@media only screen and (min-width: 640px) {");
            sb.Append("  .block-grid {");
            sb.Append("    width: 620px !important; }");
            sb.Append("  .block-grid .col {");
            sb.Append("    vertical-align: top; }");
            sb.Append("    .block-grid .col.num12 {");
            sb.Append("      width: 620px !important; }");
            sb.Append("  .block-grid.mixed-two-up .col.num4 {");
            sb.Append("    width: 204px !important; }");
            sb.Append("  .block-grid.mixed-two-up .col.num8 {");
            sb.Append("    width: 408px !important; }");
            sb.Append("  .block-grid.two-up .col {");
            sb.Append("    width: 310px !important; }");
            sb.Append("  .block-grid.three-up .col {");
            sb.Append("    width: 206px !important; }");
            sb.Append("  .block-grid.four-up .col {");
            sb.Append("    width: 155px !important; }");
            sb.Append("  .block-grid.five-up .col {");
            sb.Append("    width: 124px !important; }");
            sb.Append("  .block-grid.six-up .col {");
            sb.Append("    width: 103px !important; }");
            sb.Append("  .block-grid.seven-up .col {");
            sb.Append("    width: 88px !important; }");
            sb.Append("  .block-grid.eight-up .col {");
            sb.Append("    width: 77px !important; }");
            sb.Append("  .block-grid.nine-up .col {");
            sb.Append("    width: 68px !important; }");
            sb.Append("  .block-grid.ten-up .col {");
            sb.Append("    width: 62px !important; }");
            sb.Append("  .block-grid.eleven-up .col {");
            sb.Append("    width: 56px !important; }");
            sb.Append("  .block-grid.twelve-up .col {");
            sb.Append("    width: 51px !important; } }");
            sb.Append("@media (max-width: 640px) {");
            sb.Append("  .block-grid, .col {");
            sb.Append("    min-width: 320px !important;");
            sb.Append("    max-width: 100% !important;");
            sb.Append("    display: block !important; }");
            sb.Append("  .block-grid {");
            sb.Append("    width: calc(100% - 40px) !important; }");
            sb.Append("  .col {");
            sb.Append("    width: 100% !important; }");
            sb.Append("    .col > div {");
            sb.Append("      margin: 0 auto; }");
            sb.Append("  img.fullwidth, img.fullwidthOnMobile {");
            sb.Append("    max-width: 100% !important; }");
            sb.Append("  .no-stack .col {");
            sb.Append("    min-width: 0 !important;");
            sb.Append("    display: table-cell !important; }");
            sb.Append("  .no-stack.two-up .col {");
            sb.Append("    width: 50% !important; }");
            sb.Append("  .no-stack.mixed-two-up .col.num4 {");
            sb.Append("    width: 33% !important; }");
            sb.Append("  .no-stack.mixed-two-up .col.num8 {");
            sb.Append("    width: 66% !important; }");
            sb.Append("  .no-stack.three-up .col.num4 {");
            sb.Append("    width: 33% !important; }");
            sb.Append("  .no-stack.four-up .col.num3 {");
            sb.Append("    width: 25% !important; }");
            sb.Append("  .mobile_hide {");
            sb.Append("    min-height: 0px;");
            sb.Append("    max-height: 0px;");
            sb.Append("    max-width: 0px;");
            sb.Append("    display: none;");
            sb.Append("    overflow: hidden;");
            sb.Append("    font-size: 0px; } }");
            sb.Append("    </style>");
            sb.Append("</head>");
            sb.Append("<body class=\"clean-body\" style=\"margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #FFFFFF\">");
            sb.Append("  <style type=\"text/css\" id=\"media-query-bodytag\">");
            sb.Append("    @media (max-width: 520px) {");
            sb.Append("      .block-grid {");
            sb.Append("        min-width: 320px!important;");
            sb.Append("        max-width: 100%!important;");
            sb.Append("        width: 100%!important;");
            sb.Append("        display: block!important;");
            sb.Append("      }");
            sb.Append("      .col {");
            sb.Append("        min-width: 320px!important;");
            sb.Append("        max-width: 100%!important;");
            sb.Append("        width: 100%!important;");
            sb.Append("        display: block!important;");
            sb.Append("      }");
            sb.Append("        .col > div {");
            sb.Append("          margin: 0 auto;");
            sb.Append("        }");
            sb.Append("      img.fullwidth {");
            sb.Append("        max-width: 100%!important;");
            sb.Append("      }");
            sb.Append("			img.fullwidthOnMobile {");
            sb.Append("        max-width: 100%!important;");
            sb.Append("      }");
            sb.Append("      .no-stack .col {");
            sb.Append("				min-width: 0!important;");
            sb.Append("				display: table-cell!important;");
            sb.Append("			}");
            sb.Append("			.no-stack.two-up .col {");
            sb.Append("				width: 50%!important;");
            sb.Append("			}");
            sb.Append("			.no-stack.mixed-two-up .col.num4 {");
            sb.Append("				width: 33%!important;");
            sb.Append("			}");
            sb.Append("			.no-stack.mixed-two-up .col.num8 {");
            sb.Append("				width: 66%!important;");
            sb.Append("			}");
            sb.Append("			.no-stack.three-up .col.num4 {");
            sb.Append("				width: 33%!important;");
            sb.Append("			}");
            sb.Append("			.no-stack.four-up .col.num3 {");
            sb.Append("				width: 25%!important;");
            sb.Append("			}");
            sb.Append("      .mobile_hide {");
            sb.Append("        min-height: 0px!important;");
            sb.Append("        max-height: 0px!important;");
            sb.Append("        max-width: 0px!important;");
            sb.Append("        display: none!important;");
            sb.Append("        overflow: hidden!important;");
            sb.Append("        font-size: 0px!important;");
            sb.Append("      }");
            sb.Append("    }");
            sb.Append("  </style>");
            sb.Append("  <!--[if IE]><div class=\"ie-browser\"><![endif]-->");
            sb.Append("  <!--[if mso]><div class=\"mso-container\"><![endif]-->");
            sb.Append("  <table class=\"nl-container\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #FFFFFF;width: 100%\" cellpadding=\"0\" cellspacing=\"0\">");
            sb.Append("	<tbody>");
            sb.Append("	<tr style=\"vertical-align: top\">");
            sb.Append("		<td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">");
            sb.Append("    <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td align=\"center\" style=\"background-color: #FFFFFF;\"><![endif]-->");
            sb.Append("    <div style=\"background-color:transparent;\">");
            sb.Append("      <div style=\"Margin: 0 auto;min-width: 320px;max-width: 620px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\" class=\"block-grid two-up \">");
            sb.Append("        <div style=\"border-collapse: collapse;display: table;width: 100%;background-color:transparent;\">");
            sb.Append("          <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"background-color:transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width: 620px;\"><tr class=\"layout-full-width\" style=\"background-color:transparent;\"><![endif]-->");
            sb.Append("              <!--[if (mso)|(IE)]><td align=\"center\" width=\"310\" style=\" width:310px; padding-right: 10px; padding-left: 10px; padding-top:5px; padding-bottom:5px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;\" valign=\"top\"><![endif]-->");
            sb.Append("            <div class=\"col num6\" style=\"max-width: 320px;min-width: 310px;display: table-cell;vertical-align: top;\">");
            sb.Append("              <div style=\"background-color: transparent; width: 100% !important;\">");
            sb.Append("              <!--[if (!mso)&(!IE)]><!--><div style=\"border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 10px; padding-left: 10px;\"><!--<![endif]-->");
            sb.Append("                  ");
            sb.Append("                    <div class=\"\">");
            sb.Append("	<!--[if mso]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;\"><![endif]-->");
            sb.Append("	<div style=\"color:#555555;line-height:120%;font-family:'Montserrat', 'Trebuchet MS', 'Lucida Grande', 'Lucida Sans Unicode', 'Lucida Sans', Tahoma, sans-serif; padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;\">	");
            sb.Append("	</div>");
            sb.Append("	<!--[if mso]></td></tr></table><![endif]-->");
            sb.Append("</div>");
            sb.Append("                  ");
            sb.Append("              <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->");
            sb.Append("              </div>");
            sb.Append("            </div>");
            sb.Append("              <!--[if (mso)|(IE)]></td><td align=\"center\" width=\"310\" style=\" width:310px; padding-right: 10px; padding-left: 10px; padding-top:5px; padding-bottom:5px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;\" valign=\"top\"><![endif]-->");
            sb.Append("            <div class=\"col num6\" style=\"max-width: 320px;min-width: 310px;display: table-cell;vertical-align: top;\">");
            sb.Append("              <div style=\"background-color: transparent; width: 100% !important;\">");
            sb.Append("              <!--[if (!mso)&(!IE)]><!--><div style=\"border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 10px; padding-left: 10px;\"><!--<![endif]-->");
            sb.Append("                  ");
            sb.Append("                    <div class=\"\">");
            sb.Append("	<!--[if mso]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding-right: 0px; padding-left: 0px; padding-top: 15px; padding-bottom: 15px;\"><![endif]-->");
            sb.Append("	<div style=\"color:#555555;line-height:120%;font-family:TimesNewRoman, 'Times New Roman', Times, Baskerville, Georgia, serif; padding-right: 0px; padding-left: 0px; padding-top: 15px; padding-bottom: 15px;\">	");
            sb.Append("		<div style=\"font-size:12px;line-height:14px;font-family:TimesNewRoman, 'Times New Roman', Times, Baskerville, Georgia, serif;color:#555555;text-align:left;\"><p style=\"margin: 0;font-size: 14px;line-height: 17px;text-align: right\"><em>" + DateTime.Now.ToString("D", null) + " </em><br></p></div>	");
            sb.Append("	</div>");
            sb.Append("	<!--[if mso]></td></tr></table><![endif]-->");
            sb.Append("</div>");
            sb.Append("                  ");
            sb.Append("              <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->");
            sb.Append("              </div>");
            sb.Append("            </div>");
            sb.Append("          <!--[if (mso)|(IE)]></td></tr></table></td></tr></table><![endif]-->");
            sb.Append("        </div>");
            sb.Append("      </div>");
            sb.Append("    </div>    <div style=\"background-color:transparent;\">");
            sb.Append("      <div style=\"Margin: 0 auto;min-width: 320px;max-width: 620px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\" class=\"block-grid \">");
            sb.Append("        <div style=\"border-collapse: collapse;display: table;width: 100%;background-color:transparent;\">");
            sb.Append("          <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"background-color:transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width: 620px;\"><tr class=\"layout-full-width\" style=\"background-color:transparent;\"><![endif]-->");
            sb.Append("              <!--[if (mso)|(IE)]><td align=\"center\" width=\"620\" style=\" width:620px; padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:0px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;\" valign=\"top\"><![endif]-->");
            sb.Append("            <div class=\"col num12\" style=\"min-width: 320px;max-width: 620px;display: table-cell;vertical-align: top;\">");
            sb.Append("              <div style=\"background-color: transparent; width: 100% !important;\">");
            sb.Append("              <!--[if (!mso)&(!IE)]><!--><div style=\"border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:5px; padding-bottom:0px; padding-right: 0px; padding-left: 0px;\"><!--<![endif]-->");
            sb.Append("                  ");
            sb.Append("                    ");
            sb.Append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"divider \" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 100%;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">");
            sb.Append("    <tbody>");
            sb.Append("        <tr style=\"vertical-align: top\">");
            sb.Append("            <td class=\"divider_inner\" style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;padding-right: 10px;padding-left: 10px;padding-top: 10px;padding-bottom: 15px;min-width: 100%;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">");
            sb.Append("                <table class=\"divider_content\" height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #222222;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">");
            sb.Append("                    <tbody>");
            sb.Append("                        <tr style=\"vertical-align: top\">");
            sb.Append("                            <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">");
            sb.Append("                                <span>&#160;</span>");
            sb.Append("                            </td>");
            sb.Append("                        </tr>");
            sb.Append("                    </tbody>");
            sb.Append("                </table>");
            sb.Append("            </td>");
            sb.Append("        </tr>");
            sb.Append("    </tbody>");
            sb.Append("</table>");
            sb.Append("                  ");
            sb.Append("              <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->");
            sb.Append("              </div>");
            sb.Append("            </div>");
            sb.Append("          <!--[if (mso)|(IE)]></td></tr></table></td></tr></table><![endif]-->");
            sb.Append("        </div>");
            sb.Append("      </div>");
            sb.Append("    </div>    <div style=\"background-color:transparent;\">");
            sb.Append("      <div style=\"Margin: 0 auto;min-width: 320px;max-width: 620px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\" class=\"block-grid \">");
            sb.Append("        <div style=\"border-collapse: collapse;display: table;width: 100%;background-color:transparent;\">");
            sb.Append("          <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"background-color:transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width: 620px;\"><tr class=\"layout-full-width\" style=\"background-color:transparent;\"><![endif]-->");
            sb.Append("              <!--[if (mso)|(IE)]><td align=\"center\" width=\"620\" style=\" width:620px; padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;\" valign=\"top\"><![endif]-->");
            sb.Append("            <div class=\"col num12\" style=\"min-width: 320px;max-width: 620px;display: table-cell;vertical-align: top;\">");
            sb.Append("              <div style=\"background-color: transparent; width: 100% !important;\">");
            sb.Append("              <!--[if (!mso)&(!IE)]><!--><div style=\"border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;\"><!--<![endif]-->");
            sb.Append("                  ");
            sb.Append("                    <div align=\"center\" class=\"img-container center  autowidth  \" style=\"padding-right: 0px;  padding-left: 0px;\">");
            sb.Append("<!--[if mso]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr style=\"line-height:0px;line-height:0px;\"><td style=\"padding-right: 0px; padding-left: 0px;\" align=\"center\"><![endif]-->");
            sb.Append("  <img class=\"center  autowidth \" align=\"center\" border=\"0\" src=\"http://216.2.236.45/templateimages/okok.gif\" alt=\"Image\" title=\"Image\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: 0;height: auto;float: none;width: 100%;max-width: 250px\" width=\"250\">");
            sb.Append("<!--[if mso]></td></tr></table><![endif]-->");
            sb.Append("</div>");
            sb.Append("                  ");
            sb.Append("              <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->");
            sb.Append("              </div>");
            sb.Append("            </div>");
            sb.Append("          <!--[if (mso)|(IE)]></td></tr></table></td></tr></table><![endif]-->");
            sb.Append("        </div>");
            sb.Append("      </div>");
            sb.Append("    </div>    <div style=\"background-color:transparent;\">");
            sb.Append("      <div style=\"Margin: 0 auto;min-width: 320px;max-width: 620px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\" class=\"block-grid \">");
            sb.Append("        <div style=\"border-collapse: collapse;display: table;width: 100%;background-color:transparent;\">");
            sb.Append("          <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"background-color:transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width: 620px;\"><tr class=\"layout-full-width\" style=\"background-color:transparent;\"><![endif]-->");
            sb.Append("              <!--[if (mso)|(IE)]><td align=\"center\" width=\"620\" style=\" width:620px; padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:10px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;\" valign=\"top\"><![endif]-->");
            sb.Append("            <div class=\"col num12\" style=\"min-width: 320px;max-width: 620px;display: table-cell;vertical-align: top;\">");
            sb.Append("              <div style=\"background-color: transparent; width: 100% !important;\">");
            sb.Append("              <!--[if (!mso)&(!IE)]><!--><div style=\"border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:5px; padding-bottom:10px; padding-right: 0px; padding-left: 0px;\"><!--<![endif]-->");
            sb.Append("                  ");
            sb.Append("                    <div class=\"\">");
            sb.Append("	<!--[if mso]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 5px;\"><![endif]-->");
            sb.Append("	<div style=\"color:#000000;line-height:120%;font-family:'Lato', Tahoma, Verdana, Segoe, sans-serif; padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 5px;\">	");
            sb.Append("		<div style=\"font-size:12px;line-height:14px;font-family:Lato, Tahoma, Verdana, Segoe, sans-serif;color:#000000;text-align:left;\"><p style=\"margin: 0;font-size: 14px;line-height: 17px;text-align: center\"><strong><span style=\"font-size: 18px; line-height: 21px;\">Thank you for placing using MOXIE</span></strong></p></div>	");
            sb.Append("	</div>");
            sb.Append("	<!--[if mso]></td></tr></table><![endif]-->");
            sb.Append("</div>");
            sb.Append("                  ");
            sb.Append("                  ");
            sb.Append("                    <div class=\"\">");
            sb.Append("	<!--[if mso]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 25px;\"><![endif]-->");
            sb.Append("	<div style=\"color:#71777D;line-height:120%;font-family:'Lato', Tahoma, Verdana, Segoe, sans-serif; padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 25px;\">	");
            sb.Append("		<div style=\"font-size:12px;line-height:14px;font-family:Lato, Tahoma, Verdana, Segoe, sans-serif;color:#71777D;text-align:left;\"><p style=\"margin: 0;font-size: 14px;line-height: 17px;text-align: center\">This email contains the Work Order Confirmation document attached.</p><p style=\"margin: 0;font-size: 14px;line-height: 17px;text-align: center\">Kindly find the attached Allocation Report.</p></div>	");
            sb.Append("	</div>");
            sb.Append("	<!--[if mso]></td></tr></table><![endif]-->");
            sb.Append("</div>");
            sb.Append("                  ");
            sb.Append("              <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->");
            sb.Append("              </div>");
            sb.Append("            </div>");
            sb.Append("          <!--[if (mso)|(IE)]></td></tr></table></td></tr></table><![endif]-->");
            sb.Append("        </div>");
            sb.Append("      </div>");
            sb.Append("    </div>    <div style=\"background-color:transparent;\">");
            sb.Append("      <div style=\"Margin: 0 auto;min-width: 320px;max-width: 620px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\" class=\"block-grid \">");
            sb.Append("        <div style=\"border-collapse: collapse;display: table;width: 100%;background-color:transparent;\">");
            sb.Append("          <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"background-color:transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width: 620px;\"><tr class=\"layout-full-width\" style=\"background-color:transparent;\"><![endif]-->");
            sb.Append("              <!--[if (mso)|(IE)]><td align=\"center\" width=\"620\" style=\" width:620px; padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;\" valign=\"top\"><![endif]-->");
            sb.Append("            <div class=\"col num12\" style=\"min-width: 320px;max-width: 620px;display: table-cell;vertical-align: top;\">");
            sb.Append("              <div style=\"background-color: transparent; width: 100% !important;\">");
            sb.Append("              <!--[if (!mso)&(!IE)]><!--><div style=\"border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;\"><!--<![endif]-->");
            sb.Append("                  ");
            sb.Append("                    ");
            sb.Append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"divider \" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 100%;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">");
            sb.Append("    <tbody>");
            sb.Append("        <tr style=\"vertical-align: top\">");
            sb.Append("            <td class=\"divider_inner\" style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;padding-right: 10px;padding-left: 10px;padding-top: 10px;padding-bottom: 10px;min-width: 100%;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">");
            sb.Append("                <table class=\"divider_content\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px dotted #CCCCCC;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">");
            sb.Append("                    <tbody>");
            sb.Append("                        <tr style=\"vertical-align: top\">");
            sb.Append("                            <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">");
            sb.Append("                                <span></span>");
            sb.Append("                            </td>");
            sb.Append("                        </tr>");
            sb.Append("                    </tbody>");
            sb.Append("                </table>");
            sb.Append("            </td>");
            sb.Append("        </tr>");
            sb.Append("    </tbody>");
            sb.Append("</table>");
            sb.Append("                  ");
            sb.Append("              <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->");
            sb.Append("              </div>");
            sb.Append("            </div>");
            sb.Append("          <!--[if (mso)|(IE)]></td></tr></table></td></tr></table><![endif]-->");
            sb.Append("        </div>");
            sb.Append("      </div>");
            sb.Append("    </div>    <div style=\"background-color:transparent;\">");
            sb.Append("      <div style=\"Margin: 0 auto;min-width: 320px;max-width: 620px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\" class=\"block-grid \">");
            sb.Append("        <div style=\"border-collapse: collapse;display: table;width: 100%;background-color:transparent;\">");
            sb.Append("          <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"background-color:transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width: 620px;\"><tr class=\"layout-full-width\" style=\"background-color:transparent;\"><![endif]-->");
            sb.Append("              <!--[if (mso)|(IE)]><td align=\"center\" width=\"620\" style=\" width:620px; padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:0px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;\" valign=\"top\"><![endif]-->");
            sb.Append("            <div class=\"col num12\" style=\"min-width: 320px;max-width: 620px;display: table-cell;vertical-align: top;\">");
            sb.Append("              <div style=\"background-color: transparent; width: 100% !important;\">");
            sb.Append("              <!--[if (!mso)&(!IE)]><!--><div style=\"border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:5px; padding-bottom:0px; padding-right: 0px; padding-left: 0px;\"><!--<![endif]-->");
            sb.Append("                  ");
            sb.Append("                    ");
            sb.Append("<div align=\"center\" style=\"padding-right: 5px; padding-left: 5px; padding-bottom: 5px;\" class=\"\">");
            sb.Append("  <div style=\"line-height:5px;font-size:1px\">&#160;</div>");
            sb.Append("  <div style=\"display: table; max-width:141px;\">");
            sb.Append("  <!--[if (mso)|(IE)]><table width=\"131\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"border-collapse:collapse; padding-right: 5px; padding-left: 5px; padding-bottom: 5px;\"  align=\"center\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace: 0pt;mso-table-rspace: 0pt; width:131px;\"><tr><td width=\"32\" style=\"width:32px; padding-right: 5px;\" valign=\"top\"><![endif]-->");
            sb.Append("    <table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"32\" height=\"32\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;Margin-right: 5px\">");
            sb.Append("      <tbody><tr style=\"vertical-align: top\"><td align=\"left\" valign=\"middle\" style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">");
            sb.Append("        <a href=\"https://www.facebook.com/\" title=\"Facebook\" target=\"_blank\">");
            sb.Append("          <img src=\"http://216.2.236.45/templateimages/facebook@2x.png\" alt=\"Facebook\" title=\"Facebook\" width=\"32\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important\">");
            sb.Append("        </a>");
            sb.Append("      <div style=\"line-height:5px;font-size:1px\">&#160;</div>");
            sb.Append("      </td></tr>");
            sb.Append("    </tbody></table>");
            sb.Append("      <!--[if (mso)|(IE)]></td><td width=\"32\" style=\"width:32px; padding-right: 5px;\" valign=\"top\"><![endif]-->");
            sb.Append("    <table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"32\" height=\"32\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;Margin-right: 5px\">");
            sb.Append("      <tbody><tr style=\"vertical-align: top\"><td align=\"left\" valign=\"middle\" style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">");
            sb.Append("        <a href=\"https://twitter.com/\" title=\"Twitter\" target=\"_blank\">");
            sb.Append("          <img src=\"http://216.2.236.45/templateimages/twitter@2x.png\" alt=\"Twitter\" title=\"Twitter\" width=\"32\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important\">");
            sb.Append("        </a>");
            sb.Append("      <div style=\"line-height:5px;font-size:1px\">&#160;</div>");
            sb.Append("      </td></tr>");
            sb.Append("    </tbody></table>");
            sb.Append("      <!--[if (mso)|(IE)]></td><td width=\"32\" style=\"width:32px; padding-right: 0;\" valign=\"top\"><![endif]-->");
            sb.Append("    <table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"32\" height=\"32\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;Margin-right: 0\">");
            sb.Append("      <tbody><tr style=\"vertical-align: top\"><td align=\"left\" valign=\"middle\" style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">");
            sb.Append("        <a href=\"https://plus.google.com/\" title=\"Google+\" target=\"_blank\">");
            sb.Append("          <img src=\"http://216.2.236.45/templateimages/googleplus@2x.png\" alt=\"Google+\" title=\"Google+\" width=\"32\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important\">");
            sb.Append("        </a>");
            sb.Append("      <div style=\"line-height:5px;font-size:1px\">&#160;</div>");
            sb.Append("      </td></tr>");
            sb.Append("    </tbody></table>");
            sb.Append("    <!--[if (mso)|(IE)]></td></tr></table></td></tr></table><![endif]-->");
            sb.Append("  </div>");
            sb.Append("</div>");
            sb.Append("                  ");
            sb.Append("                  ");
            sb.Append("                    ");
            sb.Append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"divider \" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 100%;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">");
            sb.Append("    <tbody>");
            sb.Append("        <tr style=\"vertical-align: top\">");
            sb.Append("            <td class=\"divider_inner\" style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;padding-right: 10px;padding-left: 10px;padding-top: 15px;padding-bottom: 15px;min-width: 100%;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">");
            sb.Append("                <table class=\"divider_content\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px dotted #CCCCCC;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">");
            sb.Append("                    <tbody>");
            sb.Append("                        <tr style=\"vertical-align: top\">");
            sb.Append("                            <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">");
            sb.Append("                                <span></span>");
            sb.Append("                            </td>");
            sb.Append("                        </tr>");
            sb.Append("                    </tbody>");
            sb.Append("                </table>");
            sb.Append("            </td>");
            sb.Append("        </tr>");
            sb.Append("    </tbody>");
            sb.Append("</table>");
            sb.Append("                  ");
            sb.Append("              <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->");
            sb.Append("              </div>");
            sb.Append("            </div>");
            sb.Append("          <!--[if (mso)|(IE)]></td></tr></table></td></tr></table><![endif]-->");
            sb.Append("        </div>");
            sb.Append("      </div>");
            sb.Append("    </div>    <div style=\"background-color:transparent;\">");
            sb.Append("      <div style=\"Margin: 0 auto;min-width: 320px;max-width: 620px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\" class=\"block-grid \">");
            sb.Append("        <div style=\"border-collapse: collapse;display: table;width: 100%;background-color:transparent;\">");
            sb.Append("          <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"background-color:transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width: 620px;\"><tr class=\"layout-full-width\" style=\"background-color:transparent;\"><![endif]-->");
            sb.Append("              <!--[if (mso)|(IE)]><td align=\"center\" width=\"620\" style=\" width:620px; padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;\" valign=\"top\"><![endif]-->");
            sb.Append("            <div class=\"col num12\" style=\"min-width: 320px;max-width: 620px;display: table-cell;vertical-align: top;\">");
            sb.Append("              <div style=\"background-color: transparent; width: 100% !important;\">");
            sb.Append("              <!--[if (!mso)&(!IE)]><!--><div style=\"border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;\"><!--<![endif]-->");
            sb.Append("                  ");
            sb.Append("                    <div class=\"\">");
            sb.Append("	<!--[if mso]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;\"><![endif]-->");
            sb.Append("	<div style=\"color:#555555;line-height:120%;font-family:'Lato', Tahoma, Verdana, Segoe, sans-serif; padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;\">	");
            sb.Append("		<div style=\"font-size:12px;line-height:14px;font-family:Lato, Tahoma, Verdana, Segoe, sans-serif;color:#555555;text-align:left;\"><p style=\"margin: 0;font-size: 14px;line-height: 17px;text-align: center\"><span style=\"font-size: 12px; line-height: 14px;\">Copyright © 2018 Service Connections.&#160;All rights reserved.&#160;</span><br><span style=\"font-size: 12px; line-height: 14px;\"></span><span style=\"font-size: 12px; line-height: 14px;\"><a style=\"color:#71777D;text-decoration: underline;\" href=\"beefree.io\" target=\"_blank\" rel=\"noopener noreferrer\"></a></span></p></div>	");
            sb.Append("	</div>");
            sb.Append("	<!--[if mso]></td></tr></table><![endif]-->");
            sb.Append("</div>");
            sb.Append("                  ");
            sb.Append("              <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->");
            sb.Append("              </div>");
            sb.Append("            </div>");
            sb.Append("          <!--[if (mso)|(IE)]></td></tr></table></td></tr></table><![endif]-->");
            sb.Append("        </div>");
            sb.Append("      </div>");
            sb.Append("    </div>   <!--[if (mso)|(IE)]></td></tr></table><![endif]-->");
            sb.Append("		</td>");
            sb.Append("  </tr>");
            sb.Append("  </tbody>");
            sb.Append("  </table>");
            sb.Append("  <!--[if (mso)|(IE)]></div><![endif]-->");
            sb.Append("</body></html>");

            return sb.ToString();
        }
    }
}
